# .github/workflows/tests.yml

name: Python Unit Tests

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.3'

    - name: Install tools
      run: python -m pip install --upgrade pip pytest

    - name: Run tests
      run: |
        python -m unittest tests/test_game.py
